<?php
/* This file is autogenerated. Do not edit it manually
 * unless you know what you are doing. */

$SITE_SHORT_NAME = 'DBLess';
$SITE_LONG_NAME  = 'Database-less blogware';
$SITE_MAIN_TIP   = '';
?>
