<?php
/* This file is autogenerated. Do not edit it manually
 * unless you know what you are doing. */

$SITE_LICENSE_TEXT  = 'Creative Commons Attribution-ShareAlike Unported License';
$SITE_LICENSE_TITLE = 'Creative Commons Attribution-ShareAlike Unported License';
$SITE_LICENSE_URI   = 'http://creativecommons.org/licenses/by-sa/3.0/';
?>
