<?php
/**
 * @file posts_acts.php
 *
 * @brief Posts creation/edition/deletion actions
 *
 * @note I'm not happy with the method used here (and in users form).
 *       It will be so tedious to have an intermediate page for each
 *       comment, but in this case, a form per comment is needed on
 *       the same page. So I need to pass the comment ID throught the
 *       URI. Since this is the administration, no one is allowed here
 *       unless the administrator says so, but I think this is a flaw
 *       in this project.
 */

$DIR_LEVEL = 2;
require_once('../../localcfg.php');
include($DIR_CONFIG  . 'dirs.php');
include($DIR_CONFIG  . 'pages_ids.php');
include($DIR_CONFIG  . 'site_tech.php');  /* Site technical info. */
include($DIR_INCLUDE . 'common.php');     /* Truncate(... */
include($DIR_INCLUDE . 'file.php');       /* SaveFile(... */
include($DIR_INCLUDE . 'html.php');       /* html2text(... */
include($DIR_INCLUDE . 'values.php');     /* GetValueOrDefault(... */


/* Language */
if (!isset($_GET['lang']) || !file_exists($DIR_POSTS . $_GET['lang'])) {
  $Language = $SITE_DEFAULT_LANGUAGE;
} else {
  $Language = $_GET['lang'];
}


/* Default URI, just if something went wrong */
$URI = '../../admin.php?pg=' . $_b_siteinfo_ .
  '&lang=' . $Language;


/* Save site name button pressed */
if (isset($_POST['bu_save_name'])) {
  $SITE_NAME        = $_POST['site_name'];
  $SITE_DESCRIPTION = $_POST['site_description'];
  $SITE_TIP         = $_POST['site_tip'];

  /* Validation */
  $err = '';
  if ($SITE_NAME == '') {
    $err .= '&sitename=blank';
  }

  /* No errors */
  if ($err == '') {
    /* Normalization */
    $SITE_NAME        = NoQuotes(NoEntities($SITE_NAME));
    $SITE_DESCRIPTION = NoQuotes(NoEntities($SITE_DESCRIPTION));
    $SITE_TIP         = NoQuotes($SITE_TIP);

    /* Prepare file content */
    $Content = '<?php' . "\n" .
      '/* This file is autogenerated. Do not edit it manually'    . "\n" .
      ' * unless you know what you are doing. */'                 . "\n\n" .
      '$SITE_SHORT_NAME = ' . "'" . $SITE_NAME        . "'" . ';' . "\n" .
      '$SITE_LONG_NAME  = ' . "'" . $SITE_DESCRIPTION . "'" . ';' . "\n" .
      '$SITE_MAIN_TIP   = ' . "'" . $SITE_TIP         . "'" . ';' . "\n" .
      '?>' . "\n";

    /* Save file */
    $FilePath = $DIR_INFO . 'site_name.php'; /* This is one of the few
                                              * file names established by
                                              * construction. It's not a
                                              * var. */
    if (SaveFile($FilePath, $Content, 'w')) {
      $action = 'saved';

      /* --- Log action --- */
      session_start();
      if ($LOG_ACTION) {
        $log_msg = 'Site name was changed by ' .
          $_SESSION['DBL_Username'];
        AppendToLog($FILE_LOG, $log_msg);
      }
      /* --- Log action --- */
    } else {
      $action = 'fail';
    }

    $URI .= '&action=' . $action;
  } else {
    $URI .= $err;
  }

/* Save site license */
} else if (isset($_POST['bu_save_license'])) {
  $LICENSE_NAME        = $_POST['license_name'];
  $LICENSE_DESCRIPTION = $_POST['license_description'];
  $LICENSE_URI         = $_POST['license_uri'];

  /* Normalization */
  $LICENSE_NAME        = NoQuotes(NoEntities($LICENSE_NAME));
  $LICENSE_DESCRIPTION = NoQuotes(NoEntities($LICENSE_DESCRIPTION));
  $LICENSE_URI         = NoQuotes($LICENSE_URI);

  /* Prepare file content */
  $Content = '<?php' . "\n" .
    '/* This file is autogenerated. Do not edit it manually'    . "\n" .
    ' * unless you know what you are doing. */'                 . "\n\n" .
    '$SITE_LICENSE_TEXT  = ' . "'" . $LICENSE_NAME        . "'" . ';' . "\n" .
    '$SITE_LICENSE_TITLE = ' . "'" . $LICENSE_DESCRIPTION . "'" . ';' . "\n" .
    '$SITE_LICENSE_URI   = ' . "'" . $LICENSE_URI         . "'" . ';' . "\n" .
    '?>' . "\n";

  /* Save file */
  $FilePath = $DIR_INFO . 'site_license.php'; /* This is one of the few
                                               * file names established by
                                               * construction. It's not a
                                               * var. */
  if (SaveFile($FilePath, $Content, 'w')) {
    $action = 'saved';

    /* --- Log action --- */
    session_start();
    if ($LOG_ACTION) {
      $log_msg = 'Site license was changed by ' .
        $_SESSION['DBL_Username'];
      AppendToLog($FILE_LOG, $log_msg);
    }
    /* --- Log action --- */
  } else {
    $action = 'fail';
  }

  $URI .= '&action=' . $action;
}


/* Redirect automatically */
header('Location: ' . $URI);

